### ISSUE TITLE
A LICENSE.MD (which license should we use?)

### ISSUE THREAD

**Issue by idmontie** [SCMapsAndMods/general-plugin-template-project#39]
The repository should have a license file at the root of the project structure.

Which license should be used?

**Comment by idmontie** [comment]
MIT it is!

**Comment by xboi209** [comment]
May I suggest the [ISC license](https://en.wikipedia.org/wiki/ISC_license)?

**Comment by idmontie** [comment]
It seems that the ISC and MIT license are equivalent. I'll keep the MIT license for now. Feel free to submit a PR if you'd like.
